using System;
using System.Collections.Generic;
using System.Drawing;
using System.Globalization;
using System.IO;
using System.Media;
using System.Text;
using System.Threading;
using System.Web.Script.Serialization;
using System.Windows.Forms;

internal static class RitmoProgram {
    [STAThread] static void Main() { bool created; using(Mutex single=new Mutex(true,@"Local\RitmoClockApp_20261006A",out created)){if(!created)return;Application.EnableVisualStyles();Application.SetCompatibleTextRenderingDefault(false);Application.Run(new RitmoForm());} }
}

internal class RitmoForm : Form {
    static readonly string Root = AppDomain.CurrentDomain.BaseDirectory.TrimEnd(Path.DirectorySeparatorChar);
    readonly string statePath = Path.Combine(Root, "ritmo_widget_state_v2.json");
    readonly string configPath = Path.Combine(Root, "ritmo_widgets_config.json");
    readonly JavaScriptSerializer json = new JavaScriptSerializer();
    readonly System.Windows.Forms.Timer tick = new System.Windows.Forms.Timer();
    readonly Dictionary<string, WidgetForm> widgets = new Dictionary<string, WidgetForm>();
    readonly Dictionary<string, CheckBox> widgetToggles = new Dictionary<string, CheckBox>();
    Panel body, nav, content; Label title, clockHeader, heroClock, heroDate, repeatValue, repeatStatus, alarmStatus, timerValue, swValue;
    Button startRepeat, pauseRepeat, resetRepeat, startTimer, pauseTimer, resetTimer, swStart, swLap, swReset;
    NumericUpDown intervalHours, intervalMinutes, alarmHour, alarmMinute, hoursInput, minutesInput, secondsInput;
    CheckBox alarmDaily; TextBox musicLink; ListBox laps; NotifyIcon tray; ToolStripMenuItem restoreItem, repeatTrayStatus, repeatTrayAction;
    string currentView = "home", nextAlarmUtc = ""; double repeatLength = 10800, repeatRemaining = 10800, timerLength = 900, timerRemaining = 900, stopwatchSeconds = 0;
    DateTime repeatTarget = DateTime.MinValue, repeatStartAt = DateTime.MinValue, timerTarget = DateTime.MinValue, alarmAt = DateTime.MinValue;
    DateTime repeatMark = DateTime.UtcNow, timerMark = DateTime.UtcNow, stopwatchMark = DateTime.UtcNow;
    bool repeatRunning = false, repeatPaused = false, repeatScheduled = false, timerRunning = false, timerPaused = false, swRunning = false, alarmActive = false, alarmIsDaily = false;
    bool exiting = false, initialized = false;
    public RitmoForm() {
        Text = "Ritmo · Orologio"; StartPosition = FormStartPosition.CenterScreen; MinimumSize = new Size(940, 680); Size = new Size(1160, 790);
        BackColor = C("#0C121A"); ForeColor = C("#EAF2F8"); Font = new Font("Segoe UI", 10F); FormBorderStyle = FormBorderStyle.Sizable;
        BuildShell(); LoadState(); BuildTray(); BuildWidgetsFromConfig(); ShowView("home"); initialized = true;
        tick.Interval = 250; tick.Tick += Tick; tick.Start();
        FormClosing += delegate(object s, FormClosingEventArgs e) { if (!exiting) { e.Cancel = true; Hide(); if (tray != null) tray.ShowBalloonTip(1800,"Ritmo è ancora attivo","Timer e sveglie continuano in background.",ToolTipIcon.Info); } };
    }
    static Color C(string h) { return ColorTranslator.FromHtml(h); }
    static Label L(string text, float size, string color, bool bold) { return new Label { Text=text, ForeColor=C(color), Font=new Font("Segoe UI",size,bold?FontStyle.Bold:FontStyle.Regular), AutoSize=true, BackColor=Color.Transparent }; }
    static Button B(string text, string fill) { Button b=new Button{Text=text,ForeColor=C("#EAF2F8"),BackColor=C(fill),FlatStyle=FlatStyle.Flat,Font=new Font("Segoe UI",10F,FontStyle.Bold),Height=44,Cursor=Cursors.Hand,Margin=new Padding(0,0,9,0)}; b.FlatAppearance.BorderSize=0; b.FlatAppearance.MouseOverBackColor=ControlPaint.Light(C(fill),.08f); return b; }
    static Panel P(string color) { return new Panel{BackColor=C(color),Padding=new Padding(26),Margin=new Padding(0)}; }
    void BuildShell() {
        Panel root=new Panel{Dock=DockStyle.Fill,Padding=new Padding(25),BackColor=BackColor}; Controls.Add(root);
        Panel header=new Panel{Dock=DockStyle.Top,Height=62,BackColor=BackColor}; root.Controls.Add(header);
        Label mark=L("◷",29,"#9CC8E4",false); mark.Location=new Point(0,2); header.Controls.Add(mark);
        Label brand=L("RITMO",10,"#95A8B8",true); brand.Location=new Point(55,5); header.Controls.Add(brand);
        Label sub=L("Il tempo, come piace a te",12,"#D3E0E9",false); sub.Location=new Point(55,26); header.Controls.Add(sub);
        clockHeader=L("00:00:00",21,"#EAF2F8",true); clockHeader.Anchor=AnchorStyles.Top|AnchorStyles.Right; clockHeader.Location=new Point(header.Width-180,7); header.Controls.Add(clockHeader);
        header.Resize += delegate { clockHeader.Left=header.ClientSize.Width-clockHeader.Width-4; };
        nav=new Panel{Dock=DockStyle.Right,Width=218,BackColor=BackColor,Padding=new Padding(10,4,0,0)}; root.Controls.Add(nav);
        content=new Panel{Dock=DockStyle.Fill,Padding=new Padding(0,4,24,0),BackColor=BackColor}; root.Controls.Add(content);
        string[] names={"home","repeat","alarm","timer","stopwatch","world","widgets"}; string[] labels={"⌂   Ora locale","↻   Timer a ripetizione","◷   Sveglia","◴   Timer","⏱   Cronometro","◎   Ora nel mondo","▦   Widget desktop"};
        for(int i=0;i<names.Length;i++){string key=names[i]; Button b=B(labels[i],"#0C121A"); b.TextAlign=ContentAlignment.MiddleLeft;b.Dock=DockStyle.Top;b.Height=47;b.Font=new Font("Segoe UI",10F,FontStyle.Bold); b.Click += delegate{ShowView(key);}; nav.Controls.Add(b);nav.Controls.SetChildIndex(b,0); }
        Panel footer=new Panel{Dock=DockStyle.Bottom,Height=55,BackColor=BackColor}; nav.Controls.Add(footer); Button hide=B("Nascondi in background","#202C38"); hide.Dock=DockStyle.Bottom;hide.Height=38;hide.Click+=delegate{Hide();};footer.Controls.Add(hide);
    }
    void ShowView(string key) {
        currentView=key; content.SuspendLayout();content.Controls.Clear();
        Panel card=P("#151E29");card.Dock=DockStyle.Fill;content.Controls.Add(card);
        if(key=="home") BuildHome(card); else if(key=="repeat")BuildRepeat(card);else if(key=="alarm")BuildAlarm(card);else if(key=="timer")BuildTimer(card);else if(key=="stopwatch")BuildStopwatch(card);else if(key=="world")BuildWorld(card);else BuildWidgets(card);
        content.ResumeLayout();
    }
    void BuildHome(Panel p){StackPanel s=CenterStack(p);s.Controls.Add(L("ORA LOCALE",12,"#95A8B8",true));heroClock=L(DateTime.Now.ToString("HH:mm:ss"),76,"#EAF2F8",false);heroClock.Font=new Font("Segoe UI Light",78F,FontStyle.Regular);s.Controls.Add(heroClock);heroDate=L(DateTime.Now.ToString("dddd dd MMMM yyyy",new CultureInfo("it-IT")),16,"#B3C1CC",false);s.Controls.Add(heroDate);s.Controls.Add(L("Scegli una funzione dal menu per iniziare",12,"#8195A5",false)); }
    class StackPanel : FlowLayoutPanel { public StackPanel(){FlowDirection=FlowDirection.TopDown;WrapContents=false;AutoSize=true;AutoSizeMode=AutoSizeMode.GrowAndShrink;BackColor=Color.Transparent;Padding=new Padding(0);} }
    StackPanel CenterStack(Panel p){StackPanel s=new StackPanel();p.Controls.Add(s);Action layout=delegate{s.Left=Math.Max(0,(p.ClientSize.Width-s.PreferredSize.Width)/2);s.Top=Math.Max(0,(p.ClientSize.Height-s.PreferredSize.Height)/2);};p.Resize+=delegate{layout();};s.SizeChanged+=delegate{layout();};layout();return s;}
    void BuildRepeat(Panel p){StackPanel s=CenterStack(p);s.Controls.Add(L("TIMER A RIPETIZIONE",12,"#95A8B8",true));repeatValue=L("03:00:00",65,"#EAF2F8",false);repeatValue.Font=new Font("Segoe UI Light",65F);s.Controls.Add(repeatValue);repeatStatus=L("Pronto · programma l’intervallo",13,"#B3C1CC",false);s.Controls.Add(repeatStatus);
        FlowLayoutPanel scheduleRow=new FlowLayoutPanel{AutoSize=true,WrapContents=false,BackColor=Color.Transparent,Margin=new Padding(0,9,0,0)};scheduleRow.Controls.Add(L("Avvia alle",10,"#95A8B8",true));DateTimePicker repeatStartPicker=new DateTimePicker{Format=DateTimePickerFormat.Custom,CustomFormat="HH:mm",ShowUpDown=true,Width=82,Value=DateTime.Now.AddMinutes(1),Font=new Font("Segoe UI",12F),BackColor=C("#101923"),ForeColor=ForeColor,Margin=new Padding(3,0,9,0)};scheduleRow.Controls.Add(repeatStartPicker);Button scheduleRepeat=B("Programma avvio","#293D4D");scheduleRepeat.Click+=delegate{DateTime start=DateTime.Today.Add(repeatStartPicker.Value.TimeOfDay);if(start<=DateTime.Now)start=start.AddDays(1);repeatRunning=false;repeatPaused=false;repeatScheduled=true;repeatStartAt=start;repeatTarget=DateTime.MinValue;repeatRemaining=repeatLength;repeatStatus.Text=(repeatStartAt.Date==DateTime.Today?"Avvio oggi · alle ":"Avvio domani · alle ")+repeatStartAt.ToString("HH:mm");UpdateRepeatButtons();SaveState();};scheduleRow.Controls.Add(scheduleRepeat);s.Controls.Add(scheduleRow);
        FlowLayoutPanel row=new FlowLayoutPanel{AutoSize=true,WrapContents=false,BackColor=Color.Transparent,Margin=new Padding(0,15,0,4)};s.Controls.Add(row);intervalHours=Numeric((decimal)Math.Floor(repeatLength/3600),0,99,40);intervalMinutes=Numeric((decimal)Math.Floor((repeatLength%3600)/60),0,59,40);row.Controls.Add(L("Ore",10,"#95A8B8",true));row.Controls.Add(intervalHours);row.Controls.Add(L("Min",10,"#95A8B8",true));row.Controls.Add(intervalMinutes);Button apply=B("Applica intervallo","#293D4D");apply.Click+=delegate{repeatLength=Math.Max(60,(double)intervalHours.Value*3600+(double)intervalMinutes.Value*60);repeatRemaining=repeatLength;if(repeatRunning){repeatTarget=DateTime.UtcNow.AddSeconds(repeatRemaining);repeatMark=DateTime.UtcNow;} UpdateRepeatButtons();SaveState();};row.Controls.Add(apply);
        FlowLayoutPanel actions=new FlowLayoutPanel{AutoSize=true,WrapContents=false,BackColor=Color.Transparent,Margin=new Padding(0,12,0,0)};s.Controls.Add(actions);startRepeat=B("Avvia","#416B84");pauseRepeat=B("Pausa","#263541");resetRepeat=B("Da capo","#263541");actions.Controls.Add(startRepeat);actions.Controls.Add(pauseRepeat);actions.Controls.Add(resetRepeat); startRepeat.Click+=delegate{StartRepeat();}; pauseRepeat.Click+=delegate{ToggleRepeatPause();}; resetRepeat.Click+=delegate{ResetRepeat();}; Button ring=B("♪  Suono di notifica","#202C38");ring.Click+=delegate{SystemSounds.Asterisk.Play();};s.Controls.Add(ring);musicLink=new TextBox{Width=390,Text="",BackColor=C("#101923"),ForeColor=ForeColor,BorderStyle=BorderStyle.FixedSingle,Font=Font};musicLink.Text=ReadMusicLink(); if(String.IsNullOrEmpty(musicLink.Text))musicLink.Text="Link Apple Music (opzionale)"; Button saveMusic=B("Salva link Apple Music","#202C38");saveMusic.Click+=delegate{File.WriteAllText(Path.Combine(Root,"apple_music_link.txt"),musicLink.Text,Encoding.UTF8);};s.Controls.Add(musicLink);s.Controls.Add(saveMusic);
        UpdateRepeatButtons(); }
    NumericUpDown Numeric(decimal v,decimal min,decimal max,int width){return new NumericUpDown{Value=v,Minimum=min,Maximum=max,Width=width,Height=35,BackColor=C("#101923"),ForeColor=ForeColor,Font=new Font("Segoe UI",13F),BorderStyle=BorderStyle.FixedSingle};}
    void StartRepeat(){repeatScheduled=false;if(repeatPaused){repeatRunning=true;repeatPaused=false;repeatTarget=DateTime.UtcNow.AddSeconds(repeatRemaining);}else if(!repeatRunning){repeatRunning=true;repeatRemaining=repeatLength;repeatTarget=DateTime.UtcNow.AddSeconds(repeatLength);}repeatMark=DateTime.UtcNow;SaveState();UpdateRepeatButtons();UpdateTray();}
    void ToggleRepeatPause(){if(repeatScheduled){repeatScheduled=false;repeatStartAt=DateTime.MinValue;repeatRemaining=repeatLength;}else if(repeatRunning){repeatRemaining=Math.Max(0,(repeatTarget-DateTime.UtcNow).TotalSeconds);repeatRunning=false;repeatPaused=true;}else if(repeatPaused){repeatRunning=true;repeatPaused=false;repeatTarget=DateTime.UtcNow.AddSeconds(repeatRemaining);repeatMark=DateTime.UtcNow;}SaveState();UpdateRepeatButtons();UpdateTray();}
    void ResetRepeat(){repeatRunning=false;repeatPaused=false;repeatScheduled=false;repeatStartAt=DateTime.MinValue;repeatRemaining=repeatLength;repeatTarget=DateTime.MinValue;SaveState();UpdateRepeatButtons();UpdateTray();}
    void TrayRepeatAction(){if(repeatScheduled){ToggleRepeatPause();}else if(repeatRunning||repeatPaused){ToggleRepeatPause();}else{StartRepeat();}}
    void UpdateTray(){if(tray==null||repeatTrayStatus==null||repeatTrayAction==null)return;string display=repeatScheduled?"Avvio "+repeatStartAt.ToString("HH:mm")+" · "+RepeatDisplay:repeatRunning?"In corso · "+RepeatDisplay:repeatPaused?"In pausa · "+RepeatDisplay:"Timer pronto";repeatTrayStatus.Text="Timer a ripetizione: "+display;repeatTrayAction.Text=repeatScheduled?"Annulla avvio programmato":repeatRunning?"Pausa timer a ripetizione":repeatPaused?"Riprendi timer a ripetizione":"Avvia timer a ripetizione";tray.Text="Ritmo · "+display;}
    void UpdateRepeatButtons(){if(startRepeat!=null){startRepeat.Enabled=!repeatRunning;pauseRepeat.Text=repeatScheduled?"Annulla":repeatPaused?"Riprendi":"Pausa";pauseRepeat.Enabled=repeatRunning||repeatPaused||repeatScheduled;}UpdateTray();}
    void BuildAlarm(Panel p){StackPanel s=CenterStack(p);s.Controls.Add(L("SVEGLIA",12,"#95A8B8",true));s.Controls.Add(L("Imposta un orario",28,"#EAF2F8",true));FlowLayoutPanel r=new FlowLayoutPanel{AutoSize=true,WrapContents=false,BackColor=Color.Transparent};s.Controls.Add(r);alarmHour=Numeric(7,0,23,68);alarmMinute=Numeric(0,0,59,68);r.Controls.Add(alarmHour);r.Controls.Add(L(":",22,"#B3C1CC",true));r.Controls.Add(alarmMinute);alarmDaily=new CheckBox{Text="Ripeti ogni giorno",Checked=alarmIsDaily,ForeColor=C("#C6D4DF"),AutoSize=true,Margin=new Padding(2,10,2,18)};s.Controls.Add(alarmDaily);FlowLayoutPanel a=new FlowLayoutPanel{AutoSize=true,WrapContents=false,BackColor=Color.Transparent};s.Controls.Add(a);Button set=B("Imposta sveglia","#416B84"),cancel=B("Disattiva","#263541");a.Controls.Add(set);a.Controls.Add(cancel);alarmStatus=L(alarmActive?"Sveglia attiva: "+alarmAt.ToString("HH:mm"):"Nessuna sveglia impostata",12,"#B3C1CC",false);s.Controls.Add(alarmStatus);set.Click+=delegate{DateTime now=DateTime.Now;alarmAt=now.Date.AddHours((double)alarmHour.Value).AddMinutes((double)alarmMinute.Value);if(alarmAt<=now)alarmAt=alarmAt.AddDays(1);alarmIsDaily=alarmDaily.Checked;alarmActive=true;SaveState();};cancel.Click+=delegate{alarmActive=false;SaveState();};}
    void BuildTimer(Panel p){StackPanel s=CenterStack(p);s.Controls.Add(L("TIMER",12,"#95A8B8",true));s.Controls.Add(L("Conto alla rovescia",28,"#EAF2F8",true));FlowLayoutPanel r=new FlowLayoutPanel{AutoSize=true,WrapContents=false,BackColor=Color.Transparent};s.Controls.Add(r);hoursInput=Numeric(0,0,99,66);minutesInput=Numeric(15,0,59,66);secondsInput=Numeric(0,0,59,66);r.Controls.Add(hoursInput);r.Controls.Add(L(":",20,"#95A8B8",true));r.Controls.Add(minutesInput);r.Controls.Add(L(":",20,"#95A8B8",true));r.Controls.Add(secondsInput);timerValue=L("00:15:00",55,"#EAF2F8",false);timerValue.Font=new Font("Segoe UI Light",55F);s.Controls.Add(timerValue);FlowLayoutPanel a=new FlowLayoutPanel{AutoSize=true,WrapContents=false,BackColor=Color.Transparent};s.Controls.Add(a);startTimer=B("Avvia","#416B84");pauseTimer=B("Pausa","#263541");resetTimer=B("Azzera","#263541");a.Controls.Add(startTimer);a.Controls.Add(pauseTimer);a.Controls.Add(resetTimer);startTimer.Click+=delegate{if(timerPaused){timerRunning=true;timerPaused=false;timerTarget=DateTime.UtcNow.AddSeconds(timerRemaining);}else{timerLength=(double)hoursInput.Value*3600+(double)minutesInput.Value*60+(double)secondsInput.Value;timerRemaining=Math.Max(1,timerLength);timerRunning=true;timerPaused=false;timerTarget=DateTime.UtcNow.AddSeconds(timerRemaining);}SaveState();};pauseTimer.Click+=delegate{if(timerRunning){timerRemaining=Math.Max(0,(timerTarget-DateTime.UtcNow).TotalSeconds);timerRunning=false;timerPaused=true;}else if(timerPaused){timerRunning=true;timerPaused=false;timerTarget=DateTime.UtcNow.AddSeconds(timerRemaining);}SaveState();};resetTimer.Click+=delegate{timerRunning=false;timerPaused=false;timerLength=(double)hoursInput.Value*3600+(double)minutesInput.Value*60+(double)secondsInput.Value;timerRemaining=timerLength;SaveState();};}
    void BuildStopwatch(Panel p){StackPanel s=CenterStack(p);s.Controls.Add(L("CRONOMETRO",12,"#95A8B8",true));swValue=L("00:00:00.00",59,"#EAF2F8",false);swValue.Font=new Font("Segoe UI Light",59F);s.Controls.Add(swValue);FlowLayoutPanel a=new FlowLayoutPanel{AutoSize=true,WrapContents=false,BackColor=Color.Transparent};s.Controls.Add(a);swStart=B("Avvia","#416B84");swLap=B("Giro","#263541");swReset=B("Azzera","#263541");a.Controls.Add(swStart);a.Controls.Add(swLap);a.Controls.Add(swReset);laps=new ListBox{Width=340,Height=120,BackColor=C("#101923"),ForeColor=ForeColor,BorderStyle=BorderStyle.None,Font=Font};s.Controls.Add(laps);swStart.Click+=delegate{if(swRunning){stopwatchSeconds+=(DateTime.UtcNow-stopwatchMark).TotalSeconds;swRunning=false;swStart.Text="Riprendi";}else{swRunning=true;stopwatchMark=DateTime.UtcNow;swStart.Text="Pausa";}SaveState();};swLap.Click+=delegate{laps.Items.Insert(0,swValue.Text);};swReset.Click+=delegate{swRunning=false;stopwatchSeconds=0;swStart.Text="Avvia";laps.Items.Clear();SaveState();};}
    void BuildWorld(Panel p){StackPanel s=CenterStack(p);s.Controls.Add(L("OROLOGIO MONDIALE",12,"#95A8B8",true));s.Controls.Add(L("Altre città, in tempo reale",28,"#EAF2F8",true));string[] cities={"Roma|W. Europe Standard Time","Londra|GMT Standard Time","New York|Eastern Standard Time","Tokyo|Tokyo Standard Time","Sydney|AUS Eastern Standard Time"};foreach(string item in cities){string[] a=item.Split('|');Label line=L(a[0]+"     --:--:--",21,"#EAF2F8",true);line.Width=380;line.Tag=a[1];s.Controls.Add(line);}}
    void BuildWidgets(Panel p){StackPanel s=CenterStack(p);s.Controls.Add(L("WIDGET DESKTOP",12,"#95A8B8",true));s.Controls.Add(L("Scegli cosa mostrare",28,"#EAF2F8",true));s.Controls.Add(L("I widget si dispongono in basso a destra e restano sotto le altre finestre. Usa ◇ per tenerne uno in primo piano.",11,"#B3C1CC",false));foreach(string key in new string[]{"alarm","world","timer","repeat","stopwatch"}){CheckBox c=new CheckBox{Text=WidgetTitle(key),Checked=ReadWidgetConfig(key),ForeColor=C("#DCE5EC"),AutoSize=true,Font=new Font("Segoe UI",12F),Margin=new Padding(2,5,2,6),Tag=key};c.CheckedChanged+=delegate{SetWidgetConfig((string)c.Tag,c.Checked);RefreshWidgets();};widgetToggles[key]=c;s.Controls.Add(c);}s.Controls.Add(L("Ora locale è sempre visibile.",10,"#8195A5",false));}
    static string WidgetTitle(string k){switch(k){case "alarm":return "Sveglia";case "world":return "Ora nel mondo";case "timer":return "Timer";case "repeat":return "Timer a ripetizione";default:return "Cronometro";}}
    void BuildTray(){ContextMenuStrip menu=new ContextMenuStrip();restoreItem=new ToolStripMenuItem("Apri Ritmo");restoreItem.Click+=delegate{Restore();};menu.Items.Add(restoreItem);menu.Items.Add(new ToolStripSeparator());repeatTrayStatus=new ToolStripMenuItem{Enabled=false};repeatTrayAction=new ToolStripMenuItem();repeatTrayAction.Click+=delegate{TrayRepeatAction();};ToolStripMenuItem repeatResetItem=new ToolStripMenuItem("Timer a ripetizione · da capo");repeatResetItem.Click+=delegate{ResetRepeat();};menu.Items.Add(repeatTrayStatus);menu.Items.Add(repeatTrayAction);menu.Items.Add(repeatResetItem);menu.Items.Add(new ToolStripSeparator());ToolStripMenuItem exit=new ToolStripMenuItem("Esci da Ritmo");exit.Click+=delegate{ExitApp();};menu.Items.Add(exit);tray=new NotifyIcon{Text="Ritmo · sveglie e timer",Icon=SystemIcons.Information,ContextMenuStrip=menu,Visible=true};tray.DoubleClick+=delegate{Restore();};UpdateTray();}
    void Restore(){Show();WindowState=FormWindowState.Normal;Activate();BringToFront();}
    void ExitApp(){exiting=true;tick.Stop();SaveState();foreach(WidgetForm w in widgets.Values)w.Close();widgets.Clear();if(tray!=null){tray.Visible=false;tray.Dispose();}Close();}
    void BuildWidgetsFromConfig(){EnsureConfig();foreach(string k in new string[]{"clock","alarm","world","timer","repeat","stopwatch"})if(ReadWidgetConfig(k))AddWidget(k);}
    void RefreshWidgets(){foreach(string k in new string[]{"alarm","world","timer","repeat","stopwatch"}){bool on=ReadWidgetConfig(k);if(on&&!widgets.ContainsKey(k))AddWidget(k);if(!on&&widgets.ContainsKey(k)){widgets[k].Close();widgets.Remove(k);}}ReflowWidgets();}
    void AddWidget(string k){if(widgets.ContainsKey(k))return;WidgetForm w=new WidgetForm(this,k);widgets[k]=w;w.Show();ReflowWidgets();}
    void ReflowWidgets(){if(widgets.Count==0)return;Rectangle wa=Screen.PrimaryScreen.WorkingArea;int bottom=wa.Bottom-14;foreach(string k in new string[]{"clock","alarm","world","timer","repeat","stopwatch"})if(widgets.ContainsKey(k)&&widgets[k].Visible){WidgetForm w=widgets[k];w.Left=wa.Right-w.Width-14;w.Top=bottom-w.Height;bottom=w.Top-7;}}
    bool ReadWidgetConfig(string key){try{Dictionary<string,object> d=json.DeserializeObject(File.ReadAllText(configPath)) as Dictionary<string,object>;return d!=null&&d.ContainsKey(key)&&Convert.ToBoolean(d[key]);}catch{return key=="clock";}}
    void EnsureConfig(){if(!File.Exists(configPath))File.WriteAllText(configPath,"{\"clock\":true,\"alarm\":false,\"world\":false,\"timer\":false,\"repeat\":false,\"stopwatch\":false}");}
    void SetWidgetConfig(string key,bool value){Dictionary<string,object>d=new Dictionary<string,object>();foreach(string k in new string[]{"clock","alarm","world","timer","repeat","stopwatch"})d[k]=(k=="clock")||((k==key)?value:ReadWidgetConfig(k));File.WriteAllText(configPath,json.Serialize(d),new UTF8Encoding(false));}
    string ReadMusicLink(){try{return File.ReadAllText(Path.Combine(Root,"apple_music_link.txt")).Trim();}catch{return "";}}
    void LoadState(){try{if(!File.Exists(statePath))return;Dictionary<string,object>d=json.DeserializeObject(File.ReadAllText(statePath)) as Dictionary<string,object>;if(d==null)return;string n;if(d.ContainsKey("nextAlarmUtc")){n=Convert.ToString(d["nextAlarmUtc"]);DateTime dt;if(DateTime.TryParse(n,null,DateTimeStyles.AdjustToUniversal|DateTimeStyles.AssumeUniversal,out dt)){repeatTarget=dt.ToUniversalTime();repeatLength=ParseInterval(Convert.ToString(d["interval"]),10800);repeatRemaining=Math.Max(0,(repeatTarget-DateTime.UtcNow).TotalSeconds);repeatRunning=Val(d,"running",false)&&repeatRemaining>0;repeatPaused=Val(d,"paused",false);if(repeatPaused)repeatRunning=false;repeatScheduled=Val(d,"repeatScheduled",false);DateTime rs;if(repeatScheduled&&DateTime.TryParse(Convert.ToString(d.ContainsKey("repeatStartAt")?d["repeatStartAt"]:""),null,DateTimeStyles.RoundtripKind,out rs)){repeatStartAt=rs;if(repeatStartAt<=DateTime.Now)repeatScheduled=false;}}}if(d.ContainsKey("timerRemainingSeconds"))timerRemaining=Num(d,"timerRemainingSeconds",900);timerRunning=Val(d,"timerRunning",false);timerPaused=Val(d,"timerPaused",false);if(d.ContainsKey("timerEndUtc")){DateTime t;if(DateTime.TryParse(Convert.ToString(d["timerEndUtc"]),null,DateTimeStyles.AssumeUniversal|DateTimeStyles.AdjustToUniversal,out t))timerTarget=t.ToUniversalTime();}stopwatchSeconds=Num(d,"stopwatchSeconds",0);swRunning=Val(d,"stopwatchRunning",false);alarmActive=Val(d,"alarmActive",false);alarmIsDaily=Val(d,"alarmDaily",false);DateTime a;if(DateTime.TryParse(Convert.ToString(d.ContainsKey("alarmAt")?d["alarmAt"]:""),out a))alarmAt=a;}catch{} }
    static bool Val(Dictionary<string,object>d,string k,bool f){try{return d.ContainsKey(k)&&Convert.ToBoolean(d[k]);}catch{return f;}} static double Num(Dictionary<string,object>d,string k,double f){try{return Convert.ToDouble(d[k],CultureInfo.InvariantCulture);}catch{return f;}} static double ParseInterval(string s,double f){TimeSpan t;if(TimeSpan.TryParse(s,out t))return t.TotalSeconds;return f;}
    void SaveState(){if(!initialized)return;try{double rem=repeatRunning?Math.Max(0,(repeatTarget-DateTime.UtcNow).TotalSeconds):repeatRemaining;double tr=timerRunning?Math.Max(0,(timerTarget-DateTime.UtcNow).TotalSeconds):timerRemaining;string next=repeatScheduled?repeatStartAt.ToUniversalTime().ToString("o",CultureInfo.InvariantCulture):repeatTarget==DateTime.MinValue?"":repeatTarget.ToString("o",CultureInfo.InvariantCulture);string end=timerRunning?timerTarget.ToString("o",CultureInfo.InvariantCulture):"";string alarm=alarmActive?alarmAt.ToString("o",CultureInfo.InvariantCulture):"";Dictionary<string,object>d=new Dictionary<string,object>();d["updatedUtc"]=DateTime.UtcNow.ToString("o",CultureInfo.InvariantCulture);d["nextAlarmUtc"]=next;d["appRunning"]=true;d["running"]=repeatRunning;d["paused"]=repeatPaused;d["repeatScheduled"]=repeatScheduled;d["repeatStartAt"]=repeatScheduled?repeatStartAt.ToString("o",CultureInfo.InvariantCulture):"";d["remainingSeconds"]=rem;d["interval"]=TimeSpan.FromSeconds(repeatLength).ToString("c");d["timerRunning"]=timerRunning;d["timerPaused"]=timerPaused;d["timerRemainingSeconds"]=tr;d["timerEndUtc"]=end;d["alarmActive"]=alarmActive;d["alarmDaily"]=alarmIsDaily;d["alarmAt"]=alarm;d["stopwatchRunning"]=swRunning;d["stopwatchSeconds"]=stopwatchSeconds+(swRunning?(DateTime.UtcNow-stopwatchMark).TotalSeconds:0);d["widgets"]=json.DeserializeObject(File.Exists(configPath)?File.ReadAllText(configPath):"{}");string tmp=statePath+".tmp";File.WriteAllText(tmp,json.Serialize(d),new UTF8Encoding(false));if(File.Exists(statePath))File.Delete(statePath);File.Move(tmp,statePath);}catch{} }
    void Tick(object sender,EventArgs e){DateTime now=DateTime.Now;clockHeader.Text=now.ToString("HH:mm:ss");if(currentView=="home"){heroClock.Text=now.ToString("HH:mm:ss");heroDate.Text=now.ToString("dddd dd MMMM yyyy",new CultureInfo("it-IT"));}if(currentView=="repeat"){double r=repeatRunning?Math.Max(0,(repeatTarget-DateTime.UtcNow).TotalSeconds):repeatScheduled?Math.Max(0,(repeatStartAt-DateTime.Now).TotalSeconds):repeatRemaining;repeatValue.Text=Fmt(r);repeatStatus.Text=repeatScheduled?(repeatStartAt.Date==DateTime.Today?"Avvio oggi · alle ":"Avvio domani · alle ")+repeatStartAt.ToString("HH:mm"):repeatRunning?"Attivo · ogni "+TimeSpan.FromSeconds(repeatLength).ToString(@"h\:mm"):repeatPaused?"In pausa · riprendi quando vuoi":"Pronto · programma l’intervallo";}if(currentView=="timer")timerValue.Text=Fmt(timerRunning?Math.Max(0,(timerTarget-DateTime.UtcNow).TotalSeconds):timerRemaining);if(currentView=="stopwatch")swValue.Text=StopwatchText(stopwatchSeconds+(swRunning?(DateTime.UtcNow-stopwatchMark).TotalSeconds:0));if(currentView=="world"){foreach(Control c in FindLabels(content))if(c.Tag is string){string z=(string)c.Tag;try{TimeZoneInfo tz=TimeZoneInfo.FindSystemTimeZoneById(z);c.Text=z=="W. Europe Standard Time"?"Roma     "+TimeZoneInfo.ConvertTime(now,tz).ToString("HH:mm:ss"):CityName(z)+"     "+TimeZoneInfo.ConvertTime(now,tz).ToString("HH:mm:ss");}catch{}}}foreach(WidgetForm w in widgets.Values)w.UpdateText();if(repeatScheduled&&DateTime.Now>=repeatStartAt){repeatScheduled=false;repeatRunning=true;repeatPaused=false;repeatRemaining=repeatLength;repeatTarget=DateTime.UtcNow.AddSeconds(repeatLength);SystemSounds.Asterisk.Play();SaveState();}if(repeatRunning&&repeatTarget<=DateTime.UtcNow){repeatTarget=repeatTarget.AddSeconds(repeatLength);repeatRemaining=repeatLength;SystemSounds.Asterisk.Play();SaveState();}if(timerRunning&&timerTarget<=DateTime.UtcNow){timerRunning=false;timerPaused=false;timerRemaining=0;SystemSounds.Asterisk.Play();MessageBox.Show(this,"Il conto alla rovescia è terminato.","Ritmo · Timer terminato",MessageBoxButtons.OK,MessageBoxIcon.Information);}if(alarmActive&&alarmAt<=now){DateTime fired=alarmAt;if(alarmIsDaily){do{alarmAt=alarmAt.AddDays(1);}while(alarmAt<=now);}else alarmActive=false;SystemSounds.Asterisk.Play();MessageBox.Show(this,"È ora della sveglia.","Ritmo · Sveglia",MessageBoxButtons.OK,MessageBoxIcon.Information);SaveState();}if((DateTime.UtcNow-repeatMark).TotalSeconds>=1){repeatMark=DateTime.UtcNow;SaveState();UpdateTray();}}
    internal string RepeatDisplay { get { return Fmt(repeatRunning?Math.Max(0,(repeatTarget-DateTime.UtcNow).TotalSeconds):repeatScheduled?Math.Max(0,(repeatStartAt-DateTime.Now).TotalSeconds):repeatRemaining); } }
    internal string RepeatStatus { get { return repeatRunning?"Attivo · ogni "+TimeSpan.FromSeconds(repeatLength).ToString(@"h\:mm"):repeatPaused?"In pausa":repeatScheduled?(repeatStartAt.Date==DateTime.Today?"Avvio oggi · alle ":"Avvio domani · alle ")+repeatStartAt.ToString("HH:mm"):"Pronto"; } }
    internal string TimerDisplay { get { return Fmt(timerRunning?Math.Max(0,(timerTarget-DateTime.UtcNow).TotalSeconds):timerRemaining); } }
    internal string TimerStatus { get { return timerRunning?"In esecuzione":timerPaused?"In pausa":"Pronto"; } }
    internal string StopwatchDisplay { get { return StopwatchText(stopwatchSeconds+(swRunning?(DateTime.UtcNow-stopwatchMark).TotalSeconds:0)); } }
    internal string AlarmDisplay { get { return alarmActive?alarmAt.ToString("HH:mm"):"Nessuna"; } }
    internal void WidgetClosed(string key) { widgets.Remove(key); SetWidgetConfig(key,false); ReflowWidgets(); }
    static List<Control> FindLabels(Control root){List<Control> list=new List<Control>();foreach(Control c in root.Controls){if(c is Label)list.Add(c);if(c.HasChildren)list.AddRange(FindLabels(c));}return list;} static string CityName(string z){switch(z){case "GMT Standard Time":return "Londra";case "Eastern Standard Time":return "New York";case "Tokyo Standard Time":return "Tokyo";default:return "Sydney";}}
    static string Fmt(double sec){TimeSpan t=TimeSpan.FromSeconds(Math.Max(0,sec));return string.Format("{0:00}:{1:00}:{2:00}",(int)Math.Floor(t.TotalHours),t.Minutes,t.Seconds);}static string StopwatchText(double sec){TimeSpan t=TimeSpan.FromSeconds(sec);return string.Format("{0:00}:{1:00}:{2:00}.{3:00}",(int)Math.Floor(t.TotalHours),t.Minutes,t.Seconds,t.Milliseconds/10);}
}

internal class WidgetForm : Form {
    readonly RitmoForm app;readonly string key;Label primary,secondary,title;Button pin,close;bool pinned=false;
    internal WidgetForm(RitmoForm owner,string widgetKey){app=owner;key=widgetKey;Text="Ritmo · "+widgetKey;FormBorderStyle=FormBorderStyle.None;ShowInTaskbar=false;StartPosition=FormStartPosition.Manual;TopMost=false;Opacity=.68;BackColor=ColorTranslator.FromHtml("#151E29");Size=new Size(268,78);Padding=new Padding(10);Build();}
    void Build(){title=new Label{Text=key=="clock"?"ORA LOCALE":key.ToUpperInvariant(),ForeColor=ColorTranslator.FromHtml("#9CC8E4"),Font=new Font("Segoe UI",8F,FontStyle.Bold),AutoSize=true,Location=new Point(40,5)};Controls.Add(title);primary=new Label{ForeColor=ColorTranslator.FromHtml("#EAF2F8"),Font=new Font("Segoe UI Light",24F),AutoSize=true,Location=new Point(40,22)};Controls.Add(primary);secondary=new Label{ForeColor=ColorTranslator.FromHtml("#B3C1CC"),Font=new Font("Segoe UI",8F),AutoSize=true,Location=new Point(40,53)};Controls.Add(secondary);pin=new Button{Text="◇",FlatStyle=FlatStyle.Flat,ForeColor=ColorTranslator.FromHtml("#B8D9EC"),BackColor=Color.FromArgb(48,42,53,64),Size=new Size(27,29),Location=new Point(7,23)};pin.FlatAppearance.BorderSize=0;pin.Click+=delegate{pinned=!pinned;TopMost=pinned;pin.Text=pinned?"◆":"◇";};Controls.Add(pin);close=new Button{Text="×",FlatStyle=FlatStyle.Flat,ForeColor=ColorTranslator.FromHtml("#95A8B8"),BackColor=Color.Transparent,Size=new Size(25,25),Location=new Point(Width-32,5),Anchor=AnchorStyles.Top|AnchorStyles.Right};close.FlatAppearance.BorderSize=0;close.Click+=delegate{if(key!="clock"){Hide();app.WidgetClosed(key);} };Controls.Add(close);MouseDown+=Drag;title.MouseDown+=Drag;primary.MouseDown+=Drag;}
    void Drag(object sender,MouseEventArgs e){if(e.Button==MouseButtons.Left){Capture=false;Native.ReleaseCapture();Native.SendMessage(Handle,0xA1,new IntPtr(2),IntPtr.Zero);}}
    internal void UpdateText(){DateTime n=DateTime.Now;if(key=="clock"){primary.Text=n.ToString("HH:mm:ss");secondary.Text=n.ToString("dddd dd MMMM",new CultureInfo("it-IT"));}else if(key=="repeat"){primary.Text=app.RepeatDisplay;secondary.Text=app.RepeatStatus;}else if(key=="timer"){primary.Text=app.TimerDisplay;secondary.Text=app.TimerStatus;}else if(key=="stopwatch"){primary.Text=app.StopwatchDisplay;secondary.Text="Cronometro";}else if(key=="alarm"){primary.Text=app.AlarmDisplay;secondary.Text="Sveglia";}else{primary.Text=TimeZoneInfo.ConvertTime(n,TimeZoneInfo.FindSystemTimeZoneById("GMT Standard Time")).ToString("HH:mm:ss");secondary.Text="Londra";}}
    protected override void OnShown(EventArgs e){base.OnShown(e);UpdateText();}
    static class Native{[System.Runtime.InteropServices.DllImport("user32.dll")]internal static extern bool ReleaseCapture();[System.Runtime.InteropServices.DllImport("user32.dll")]internal static extern IntPtr SendMessage(IntPtr h,int m,IntPtr w,IntPtr l);}
}






